import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CAD_LISTINGS = [
  {
    id: 'cad-sourdough-box',
    title: 'Artisan Sourdough & Croissant Surprise Box',
    description: 'European artisan rustic sourdough loaves, buttery croissants, pain au chocolat, and daily fruit danishes.',
    category: 'Pastry',
    photoUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1000&q=80',
    originalPrice: 16.00,
    price: 4.99,
    discount: '69% OFF',
    bagsAvailable: 4,
    bagsSold: 18,
    status: 'ACTIVE',
    pickupDate: 'Today',
    pickupStart: '6:30 PM',
    pickupEnd: '7:30 PM',
    dietaryTags: ['vegetarian', 'artisan', 'bakery'],
    co2SavedKg: 2.5,
    storeId: 'st_cad',
    storeName: 'CAD Bakery',
  },
  {
    id: 'cad-croissant-bundle',
    title: 'French Butter Croissant & Viennoiserie Bag',
    description: 'Pure French butter croissants, almond escargot pastries, chocolate swirls, and buttery brioche buns.',
    category: 'Pastry',
    photoUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80',
    originalPrice: 13.50,
    price: 3.99,
    discount: '70% OFF',
    bagsAvailable: 5,
    bagsSold: 22,
    status: 'ACTIVE',
    pickupDate: 'Today',
    pickupStart: '6:00 PM',
    pickupEnd: '7:30 PM',
    dietaryTags: ['vegetarian', 'pastry'],
    co2SavedKg: 2.1,
    storeId: 'st_cad',
    storeName: 'CAD Bakery',
  },
  {
    id: 'cad-rustic-breads',
    title: 'Rustic Country Sourdough & Baguette Pack',
    description: 'Two full-size artisan sourdough boules and crispy European baguettes freshly baked with organic wheat flour.',
    category: 'Pastry',
    photoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    originalPrice: 12.00,
    price: 3.50,
    discount: '71% OFF',
    bagsAvailable: 3,
    bagsSold: 14,
    status: 'ACTIVE',
    pickupDate: 'Today',
    pickupStart: '6:30 PM',
    pickupEnd: '8:00 PM',
    dietaryTags: ['vegan', 'organic'],
    co2SavedKg: 1.8,
    storeId: 'st_cad',
    storeName: 'CAD Bakery',
  },
  {
    id: 'cad-sweet-dessert-box',
    title: 'Sweet Tartlets, Cakes & Danish Treats',
    description: 'Fresh fruit tarts, custard brioches, cinnamon glazed knots, and seasonal pastry slices from today.',
    category: 'Dessert',
    photoUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    originalPrice: 15.00,
    price: 4.50,
    discount: '70% OFF',
    bagsAvailable: 3,
    bagsSold: 9,
    status: 'ACTIVE',
    pickupDate: 'Today',
    pickupStart: '7:00 PM',
    pickupEnd: '8:30 PM',
    dietaryTags: ['dessert', 'sweet'],
    co2SavedKg: 1.9,
    storeId: 'st_cad',
    storeName: 'CAD Bakery',
  },
  {
    id: 'cad-savory-focaccia',
    title: 'Savory Focaccia & Stuffed Brioche Box',
    description: 'Rosemary sea salt focaccia squares, ham and gruyere melt twists, and savory olive rolls.',
    category: 'Food',
    photoUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    originalPrice: 14.00,
    price: 4.20,
    discount: '70% OFF',
    bagsAvailable: 2,
    bagsSold: 11,
    status: 'ACTIVE',
    pickupDate: 'Today',
    pickupStart: '6:00 PM',
    pickupEnd: '7:30 PM',
    dietaryTags: ['savory', 'meals'],
    co2SavedKg: 2.0,
    storeId: 'st_cad',
    storeName: 'CAD Bakery',
  },
  {
    id: 'cad-coffee-pastry-pair',
    title: 'Barista Cold Brew & Afternoon Pastry Pair',
    description: 'Bottled organic cold brew coffee or iced matcha latte paired with two fresh breakfast pastries.',
    category: 'Drinks',
    photoUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    originalPrice: 9.00,
    price: 2.90,
    discount: '68% OFF',
    bagsAvailable: 6,
    bagsSold: 15,
    status: 'ACTIVE',
    pickupDate: 'Today',
    pickupStart: '5:30 PM',
    pickupEnd: '7:00 PM',
    dietaryTags: ['drinks', 'cafe'],
    co2SavedKg: 1.2,
    storeId: 'st_cad',
    storeName: 'CAD Bakery',
  },
];

async function main() {
  console.log('Seeding 6 aligned CAD Bakery listings...');
  for (const item of CAD_LISTINGS) {
    await prisma.listing.upsert({
      where: { id: item.id },
      update: {
        title: item.title,
        description: item.description,
        category: item.category,
        photoUrl: item.photoUrl,
        originalPrice: item.originalPrice,
        price: item.price,
        discount: item.discount,
        bagsAvailable: item.bagsAvailable,
        bagsSold: item.bagsSold,
        status: item.status,
        pickupDate: item.pickupDate,
        pickupStart: item.pickupStart,
        pickupEnd: item.pickupEnd,
        dietaryTags: item.dietaryTags,
        co2SavedKg: item.co2SavedKg,
        storeId: item.storeId,
        storeName: item.storeName,
      },
      create: {
        id: item.id,
        title: item.title,
        description: item.description,
        category: item.category,
        photoUrl: item.photoUrl,
        originalPrice: item.originalPrice,
        price: item.price,
        discount: item.discount,
        bagsAvailable: item.bagsAvailable,
        bagsSold: item.bagsSold,
        status: item.status,
        pickupDate: item.pickupDate,
        pickupStart: item.pickupStart,
        pickupEnd: item.pickupEnd,
        dietaryTags: item.dietaryTags,
        co2SavedKg: item.co2SavedKg,
        storeId: item.storeId,
        storeName: item.storeName,
      },
    });
    console.log(`✅ Upserted ${item.id} - ${item.title}`);
  }

  // Also ensure old irrelevant fast-food listings do not show CAD Bakery
  const remapped = await prisma.listing.updateMany({
    where: {
      storeId: 'st_cad',
      id: { notIn: CAD_LISTINGS.map(l => l.id) },
      OR: [
        { title: { contains: 'Burger', mode: 'insensitive' } },
        { title: { contains: 'Chicken', mode: 'insensitive' } },
        { title: { contains: 'Tacos', mode: 'insensitive' } },
        { title: { contains: 'Pizza', mode: 'insensitive' } },
        { title: { contains: 'Dogs', mode: 'insensitive' } },
        { title: { contains: 'Kebab', mode: 'insensitive' } },
        { title: { contains: 'Nuggets', mode: 'insensitive' } },
        { title: { contains: 'Subs', mode: 'insensitive' } },
        { title: { contains: 'Wraps', mode: 'insensitive' } },
        { title: { contains: 'Fries', mode: 'insensitive' } },
      ],
    },
    data: {
      storeName: 'Street Eats Deli',
      storeId: null,
    },
  });
  console.log(`Cleaned up ${remapped.count} non-bakery listings from CAD Bakery.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
